import React, { createContext, useContext, ReactNode } from 'react'
import { useKV } from '@github/spark/hooks'

type Language = 'en' | 'de' | 'zh' | 'fr'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation dictionaries
const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.marketplaces': 'Marketplaces',
    'nav.products': 'Products',
    'nav.inventory': 'Inventory Sync',
    'nav.shop': 'Shop',
    'nav.blog': 'Blog',
    'nav.whatsapp': 'WhatsApp',
    'nav.agents': 'AI Agents',
    'nav.admin': 'Admin Panel',
    'nav.account': 'My Account',
    'nav.cart': 'Shopping Cart',
    'nav.orders': 'My Orders',
    'nav.logout': 'Logout',
    'nav.login': 'Login',
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.client': 'Website',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.configure': 'Configure',
    'common.demo': 'Demo',
    'common.performance': 'Performance',
    'common.training': 'Training',
    'common.examples': 'Examples',
    'common.configuration': 'Configuration',
    
    // Agent Demo Panel
    'agent.tryAgent': 'Try the Agent',
    'agent.enterInput': 'Enter your own input to see how the agent processes it',
    'agent.input': 'Input',
    'agent.runDemo': 'Run Demo',
    'agent.processing': 'Processing...',
    'agent.demoOutput': 'Demo Output',
    'agent.capabilities': 'Agent Capabilities',
    'agent.liveDemo': 'Live Demo',
    'agent.realTimePerformance': 'Real-time Performance',
    'agent.liveMetrics': 'Live metrics and performance indicators for this agent',
    'agent.todayPerformance': "Today's Performance",
    'agent.tasksCompleted': 'Tasks Completed',
    'agent.successRate': 'Success Rate',
    'agent.avgResponseTime': 'Avg Response Time',
    'agent.errorRate': 'Error Rate',
    'agent.usageTrends': 'Usage Trends (7 days)',
    'agent.businessImpact': 'Business Impact',
    'agent.recentActivity': 'Recent Activity',
    'agent.enterInputDemo': 'Please enter input for the demo',
    'agent.initializingAgent': 'Initializing agent...',
    'agent.processingInput': 'Processing input...',
    'agent.generatingOutput': 'Generating output...',
    'agent.demoCompleted': 'Demo completed! Check the output below.',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.status': 'Status',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.total': 'Total',
    'common.view': 'View',
    'common.back': 'Back',
    
    // Admin Panel
    'admin.title': 'Admin Control Center',
    'admin.overview': 'System Overview',
    'admin.users': 'User Management',
    'admin.settings': 'Global Settings',
    'admin.analytics': 'Advanced Analytics',
    'admin.logs': 'System Logs',
    'admin.coreManagement': 'Core Management',
    'admin.configuration': 'Configuration',
    'admin.aiAutomation': 'AI & Automation',
    'admin.systemMonitoring': 'System & Monitoring',
    'admin.shopConfig': 'Shop Configuration',
    'admin.blogConfig': 'Blog Configuration',
    'admin.sync': 'Synchronization',
    'admin.monitoring': 'Monitoring',
    'admin.userManagement': 'User Management System',
    'admin.userManagementDesc': 'Manage user accounts, permissions, and access control',
    
    // Shop
    'shop.title': 'Goodlink Store',
    'shop.categories': 'Categories',
    'shop.featured': 'Featured Products',
    'shop.bestsellers': 'Best Sellers',
    'shop.new': 'New Arrivals',
    'shop.addToCart': 'Add to Cart',
    'shop.buyNow': 'Buy Now',
    'shop.outOfStock': 'Out of Stock',
    'shop.inStock': 'In Stock',
    'shop.productDetails': 'Product Details',
    'shop.reviews': 'Customer Reviews',
    'shop.relatedProducts': 'Related Products',
    'shop.checkout': 'Checkout',
    'shop.cart': 'Shopping Cart',
    'shop.cartEmpty': 'Your cart is empty',
    'shop.continueShopping': 'Continue Shopping',
    'shop.proceedToCheckout': 'Proceed to Checkout',
    
    // User Account
    'user.profile': 'Profile',
    'user.orders': 'Order History',
    'user.addresses': 'Addresses',
    'user.payment': 'Payment Methods',
    'user.preferences': 'Preferences',
    'user.notifications': 'Notifications',
    'user.security': 'Security',
    'user.welcome': 'Welcome back',
    
    // AI Agents
    'agents.title': 'AI Agent Control Center',
    'agents.active': 'Active Agents',
    'agents.training': 'Training',
    'agents.success': 'Avg Success Rate',
    'agents.processed': 'Total Processed',
    'agents.social': 'Social Media',
    'agents.messaging': 'Messaging',
    'agents.content': 'Content',
    'agents.pricing': 'Pricing',
    'agents.analytics': 'Analytics',
    'agents.forecasting': 'Forecasting',
    'agents.support': 'Support',
    
    // Specialized Agents
    'agents.allAgents': 'All Agents',
    'agents.specializedAgents': 'Specialized Agents',
    'agents.categoryExperts': 'Product Category Experts',
    'agents.allAgentsDesc': 'Overview of all AI agents',
    'agents.specializedAgentsDesc': 'Medical & automotive experts',
    'agents.syncInventory': 'Inventory Sync',
    'agents.syncInventoryDesc': 'Marketplace inventory synchronization',
    'agents.globalConfig': 'Global Configuration',
    'agents.globalConfigDesc': 'Global agent settings',
    
    'Specialized AI Agents': 'Specialized AI Agents',
    'Expert knowledge for medical devices and automotive components': 'Expert knowledge for medical devices and automotive components',
    'Configure': 'Configure',
    'Performance': 'Performance',
    'Tasks': 'Tasks',
    'Active': 'Active',
    'Inactive': 'Inactive',
    'Training': 'Training',
    'Error': 'Error',
    'Unknown': 'Unknown',
    'Agent status updated': 'Agent status updated',
    'Agent training started': 'Agent training started',
    'Agent training completed': 'Agent training completed',
    'Configuration updated': 'Configuration updated',
    'Pause': 'Pause',
    'Activate': 'Activate',
    'Retrain': 'Retrain',
    'Overview': 'Overview',
    'Expertise': 'Expertise',
    'Configuration': 'Configuration',
    'Status & Metrics': 'Status & Metrics',
    'Tasks Completed': 'Tasks Completed',
    'Category': 'Category',
    'Compliance Standards': 'Compliance Standards',
    'Supported Languages': 'Supported Languages',
    'Core Expertise Areas': 'Core Expertise Areas',
    'Knowledge Base': 'Knowledge Base',
    'Standards Documents': 'Standards Documents',
    'Product Specifications': 'Product Specifications',
    'Compliance Guides': 'Compliance Guides',
    'Last Knowledge Update': 'Last Knowledge Update',
    'Response Quality': 'Response Quality',
    'Accuracy': 'Accuracy',
    'Compliance Check': 'Compliance Check',
    'User Satisfaction': 'User Satisfaction',
    'Task Statistics': 'Task Statistics',
    'Tasks Today': 'Tasks Today',
    'Average Response Time': 'Average Response Time',
    'Success Rate': 'Success Rate',
    'Error Rate': 'Error Rate',
    'Model Configuration': 'Model Configuration',
    'AI Model': 'AI Model',
    'Temperature': 'Temperature',
    'Max Tokens': 'Max Tokens',
    'Specialization Settings': 'Specialization Settings',
    'Focus Area': 'Focus Area',
    'Medical Devices': 'Medical Devices',
    'Automotive Components': 'Automotive Components',
    'Connectors & Cables': 'Connectors & Cables',
    'Motors & Sensors': 'Motors & Sensors',
    'Active Compliance Standards': 'Active Compliance Standards',
    'Custom Instructions': 'Custom Instructions',
    'Enter specific instructions for this agent...': 'Enter specific instructions for this agent...',
    'Cancel': 'Cancel',
    'Save Configuration': 'Save Configuration',
    'Configuration saved': 'Configuration saved',
    'Management': 'Management',
    'Live Demo': 'Live Demo',
    'Basic Demo': 'Basic Demo',
    'Advanced Demo': 'Advanced Demo',
    'Advanced Specialized Agents Demo': 'Advanced Specialized Agents Demo',
    'Test specialized AI agents with real Spark LLM integration': 'Test specialized AI agents with real Spark LLM integration',
    'Specialized Agents Demo': 'Specialized Agents Demo',
    'Test specialized AI agents with your product data': 'Test specialized AI agents with your product data',
    'Product Information': 'Product Information',
    'Select Specialized Agent': 'Select Specialized Agent',
    'Product Name': 'Product Name',
    'Product Description': 'Product Description',
    'Technical Specifications': 'Technical Specifications',
    'Analyze Product': 'Analyze Product',
    'Check Compliance': 'Check Compliance',
    'Generate Content': 'Generate Content',
    'Multi-Language': 'Multi-Language',
    'Agent Tasks & Results': 'Agent Tasks & Results',
    'No tasks yet. Run an agent task to see results.': 'No tasks yet. Run an agent task to see results.',
    
    // Dashboard
    'dashboard.revenue': 'Total Revenue',
    'dashboard.orders': 'Active Orders',
    'dashboard.buybox': 'Buy Box %',
    'dashboard.automations': 'AI Automations',
    'dashboard.performance': 'Performance Trends',
    'dashboard.marketplaceRevenue': 'Revenue by Marketplace',
    
    // Agent Performance
    'agents.performance.title': 'Agent Performance Dashboard',
    'agents.performance.subtitle': 'Monitor and optimize AI agent performance with A/B testing',
    
    // Chat
    'chat.aiAssistant': 'AI Assistant',
    'chat.onlineNow': 'Online now',
    'chat.typeMessage': 'Type your message...',
    'chat.helpful': 'Helpful?',
    'chat.helpfulFeedback': 'Helpful feedback received',
    'chat.feedbackReceived': 'Feedback received',
    'chat.poweredBy': 'Powered by Goodlink AI • Available 24/7',
    'chat.showPopularProducts': 'Show me popular products',
    'chat.findMedicalDevices': 'Help me find medical devices',
    'chat.findAutomotiveParts': 'Show automotive components',
    'chat.complianceCerts': 'Compliance certificates',
    'chat.volumePricing': 'Volume pricing options',
    'chat.technicalDocs': 'Technical documentation',
    'chat.bestDeals': 'What are your best deals?',
    'chat.customerSupport': 'I need customer support',
    'chat.shippingInfo': 'Tell me more about shipping',
    'chat.productCategories': 'Show me product categories',
    'chat.returnsInfo': 'How do returns work?',
    'chat.humanSupport': 'Contact human support',
    'chat.tryAgain': 'Try again',
    'chat.errorResponse': "I apologize, I'm having trouble responding right now. Please try again or contact our human support team.",
    'chat.clearChat': 'Clear conversation',
    'chat.closeChat': 'Close chat',
    'chat.minimize': 'Minimize',
    'chat.maximize': 'Maximize',
    'chat.restore': 'Restore',
    'chat.escToClose': 'ESC to close',
    
    // System Status
    'system.online': 'System Online',
    'system.offline': 'System Offline',
    'system.maintenance': 'Maintenance Mode',
    
    // Language names
    'lang.english': 'English',
    'lang.german': 'Deutsch',
    'lang.chinese': '中文',
    'lang.french': 'Français',
    
    // Login & Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.company': 'Company',
    'auth.phone': 'Phone Number',
    'auth.rememberMe': 'Remember me',
    'auth.forgotPassword': 'Forgot password?',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.signUp': 'Sign up',
    'auth.signIn': 'Sign in',
    'auth.signOut': 'Sign out',
    'auth.createAccount': 'Create Account',
    'auth.welcome': 'Welcome to Goodlink Germany',
    'auth.welcomeBack': 'Welcome back',
    'auth.loginDesc': 'Sign in to access premium medical devices and automotive components',
    'auth.registerDesc': 'Join thousands of satisfied B2B partners',
    'auth.terms': 'I agree to the Terms of Service and Privacy Policy',
    'auth.accountType': 'Account Type',
    'auth.individual': 'Individual Customer',
    'auth.business': 'Business Account',
    'auth.customerType': 'Customer Type',
    'auth.newCustomer': 'New Customer',
    'auth.returningCustomer': 'Returning Customer',
    'auth.loggedOut': 'Logged out successfully',
    
    // Account Management
    'account.profile': 'Profile',
    'account.orders': 'My Orders',
    'account.settings': 'Settings',
    
    // Client Website
    'client.aboutTitle': 'About Goodlink Germany',
    'client.aboutDesc': 'Good-Link Germany GmbH is located in the heart of Europe in Cologne, Germany. We are the first Good-Link branch out of China, founded in 2020 in cooperation with German shareholders and management.',
    'client.ourMission': 'Our Mission',
    'client.missionDesc': 'Good-Link Germany will become the best channel for European companies who wish to cooperate with partners in China.',
    'client.ourValues': 'Our Values',
    'client.heroTitle': 'Medical & Automotive Excellence',
    'client.heroSubtitle': 'Premium medical devices and automotive components. Your trusted bridge between Europe and China since 2020.',
    'client.browseCatalog': 'Browse Catalog',
    'client.learnMore': 'Learn More',
    'client.whyChoose': 'Why Choose Goodlink Germany?',
    'client.whyChooseDesc': 'Experience the future of B2B sourcing with our innovative features and commitment to excellence.',
    'client.medicalGrade': 'Medical Grade Quality',
    'client.medicalGradeDesc': 'Certified medical devices and automotive components meeting EU/CE standards',
    'client.chinaBridge': 'China-EU Bridge',
    'client.chinaBridgeDesc': 'Direct sourcing from trusted manufacturers in Shenzhen, Shanghai, and Hong Kong',
    'client.compliance': 'Compliance Assured',
    'client.complianceDesc': 'Full regulatory compliance for medical devices (MDR/CE) and automotive (EMC/ROHS)',
    'client.expertSupport': 'Expert Support',
    'client.expertSupportDesc': 'Technical support from specialists in German, English, and Chinese',
    'client.shopByCategory': 'Shop by Category',
    'client.shopByCategoryDesc': 'Explore our diverse range of products across multiple categories.',
    'client.medicalDevices': 'Medical Devices',
    'client.automotiveParts': 'Automotive Parts',
    'client.connectorsCables': 'Connectors & Cables',
    'client.motorsSensors': 'Motors & Sensors',
    'client.mechanicalComponents': 'Mechanical Components',
    'client.readyToStart': 'Ready to Start Shopping?',
    'client.readyToStartDesc': 'Join thousands of satisfied customers and discover amazing products with our AI-powered sourcing experience.',
    'client.browseProducts': 'Browse Products',
    'client.readBlog': 'Read Our Blog',
    'client.businessCulture': 'Our Business Culture',
    'client.personalRelationships': 'Good personal relationships and a reliable way of working characterises our approach to our partners',
    'client.honestCommunication': 'Realistic and honest communication ensure an effective and trustful cooperation',
    'client.culturalBridges': 'We are aware of cultural differences and enjoy building bridges to cross them',
    'client.ourTeam': 'Our Team',
    'client.officesChina': 'Offices in China',
    'client.officesGermany': 'Offices in Germany',
    'client.focusMedical': 'Focus on Medical',
    'client.warehouses': 'Warehouses',
    'client.goodlinkChina': 'Good-Link China',
    'client.goodlinkChinaDesc': 'Founded in 2004, Good-Link China operates across four cities in China with a team of 78 employees. Specialized in the automotive and medical sectors, we are proud of our established and extensive network of suppliers and customers.',
    'client.components': 'components',
    'client.partners': 'B2B Partners',
    'client.experience': 'Years Experience',
    'client.revenue': 'Revenue 2023',
    
    // Cart & Shopping
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.emptyDesc': 'Add some products to get started',
    'cart.item': 'item',
    'cart.items': 'items',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.tax': 'Tax',
    'cart.total': 'Total',
    'cart.remove': 'Remove',
    'cart.update': 'Update',
    'cart.checkout': 'Proceed to Checkout',
    'cart.continueShopping': 'Continue Shopping',
    'cart.addedToCart': 'Added to cart',
    'cart.removedFromCart': 'Removed from cart',
    'cart.quantityUpdated': 'Quantity updated',
    
    // Agent Status
    'agents.statusUpdated': 'Agent status updated',
    'agents.configSaved': 'Configuration saved',
    'agents.successRate': 'Success Rate',
    'agents.tasks': 'Tasks',
    'agents.pause': 'Pause',
    'agents.activate': 'Activate',
  },
  
  de: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.marketplaces': 'Marktplätze',
    'nav.products': 'Produkte',
    'nav.inventory': 'Inventar Sync',
    'nav.shop': 'Shop',
    'nav.blog': 'Blog',
    'nav.whatsapp': 'WhatsApp',
    'nav.agents': 'KI-Agenten',
    'nav.admin': 'Admin Panel',
    'nav.account': 'Mein Konto',
    'nav.cart': 'Warenkorb',
    'nav.orders': 'Meine Bestellungen',
    'nav.logout': 'Abmelden',
    'nav.login': 'Anmelden',
    'nav.home': 'Start',
    'nav.about': 'Über uns',
    'nav.contact': 'Kontakt',
    'nav.client': 'Website',
    
    // Common
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.add': 'Hinzufügen',
    'common.search': 'Suchen',
    'common.filter': 'Filter',
    'common.export': 'Exportieren',
    'common.import': 'Importieren',
    'common.configure': 'Konfigurieren',
    'common.active': 'Aktiv',
    'common.inactive': 'Inaktiv',
    'common.status': 'Status',
    'common.price': 'Preis',
    'common.quantity': 'Menge',
    'common.total': 'Gesamt',
    'common.view': 'Ansehen',
    'common.back': 'Zurück',
    
    // Admin Panel
    'admin.title': 'Admin Kontrollzentrum',
    'admin.overview': 'Systemübersicht',
    'admin.users': 'Benutzerverwaltung',
    'admin.settings': 'Globale Einstellungen',
    'admin.analytics': 'Erweiterte Analytik',
    'admin.logs': 'Systemprotokolle',
    'admin.coreManagement': 'Kernverwaltung',
    'admin.configuration': 'Konfiguration',
    'admin.aiAutomation': 'KI & Automatisierung',
    'admin.systemMonitoring': 'System & Überwachung',
    'admin.shopConfig': 'Shop-Konfiguration',
    'admin.blogConfig': 'Blog-Konfiguration',
    'admin.sync': 'Synchronisation',
    'admin.monitoring': 'Überwachung',
    'admin.userManagement': 'Benutzerverwaltungssystem',
    'admin.userManagementDesc': 'Verwalten Sie Benutzerkonten, Berechtigungen und Zugriffskontrolle',
    
    // Shop
    'shop.title': 'Goodlink Store',
    'shop.categories': 'Kategorien',
    'shop.featured': 'Empfohlene Produkte',
    'shop.bestsellers': 'Bestseller',
    'shop.new': 'Neuheiten',
    'shop.addToCart': 'In den Warenkorb',
    'shop.buyNow': 'Jetzt kaufen',
    'shop.outOfStock': 'Nicht vorrätig',
    'shop.inStock': 'Auf Lager',
    'shop.productDetails': 'Produktdetails',
    'shop.reviews': 'Kundenbewertungen',
    'shop.relatedProducts': 'Ähnliche Produkte',
    'shop.checkout': 'Zur Kasse',
    'shop.cart': 'Warenkorb',
    'shop.cartEmpty': 'Ihr Warenkorb ist leer',
    'shop.continueShopping': 'Weiter einkaufen',
    'shop.proceedToCheckout': 'Zur Kasse gehen',
    
    // User Account
    'user.profile': 'Profil',
    'user.orders': 'Bestellhistorie',
    'user.addresses': 'Adressen',
    'user.payment': 'Zahlungsmethoden',
    'user.preferences': 'Einstellungen',
    'user.notifications': 'Benachrichtigungen',
    'user.security': 'Sicherheit',
    'user.welcome': 'Willkommen zurück',
    
    // AI Agents
    'agents.title': 'KI-Agenten Kontrollzentrum',
    'agents.active': 'Aktive Agenten',
    'agents.training': 'Training',
    'agents.success': 'Durchschn. Erfolgsrate',
    'agents.processed': 'Gesamt verarbeitet',
    'agents.social': 'Social Media',
    'agents.messaging': 'Messaging',
    'agents.content': 'Inhalt',
    'agents.pricing': 'Preisgestaltung',
    'agents.analytics': 'Analytik',
    'agents.forecasting': 'Prognose',
    'agents.support': 'Support',
    
    // Agent Demo Panel (German)
    'common.demo': 'Demo',
    'common.performance': 'Leistung',
    'common.training': 'Training',
    'common.examples': 'Beispiele',
    'common.configuration': 'Konfiguration',
    'agent.tryAgent': 'Agent testen',
    'agent.enterInput': 'Geben Sie Ihre eigene Eingabe ein, um zu sehen, wie der Agent sie verarbeitet',
    'agent.input': 'Eingabe',
    'agent.runDemo': 'Demo starten',
    'agent.processing': 'Verarbeitung...',
    'agent.demoOutput': 'Demo-Ausgabe',
    'agent.capabilities': 'Agent-Fähigkeiten',
    'agent.liveDemo': 'Live Demo',
    'agent.realTimePerformance': 'Echtzeit-Leistung',
    'agent.liveMetrics': 'Live-Metriken und Leistungsindikatoren für diesen Agent',
    'agent.todayPerformance': 'Heutige Leistung',
    'agent.tasksCompleted': 'Aufgaben abgeschlossen',
    'agent.successRate': 'Erfolgsrate',
    'agent.avgResponseTime': 'Durchschn. Antwortzeit',
    'agent.errorRate': 'Fehlerrate',
    'agent.usageTrends': 'Nutzungstrends (7 Tage)',
    'agent.businessImpact': 'Geschäftsauswirkungen',
    'agent.recentActivity': 'Letzte Aktivitäten',
    'agent.enterInputDemo': 'Bitte geben Sie eine Eingabe für die Demo ein',
    'agent.initializingAgent': 'Agent wird initialisiert...',
    'agent.processingInput': 'Eingabe wird verarbeitet...',
    'agent.generatingOutput': 'Ausgabe wird generiert...',
    'agent.demoCompleted': 'Demo abgeschlossen! Überprüfen Sie die Ausgabe unten.',
    
    // Specialized Agents
    'agents.allAgents': 'Alle Agenten',
    'agents.specializedAgents': 'Spezialisierte Agenten',
    'agents.categoryExperts': 'Produktkategorie-Experten',
    'agents.allAgentsDesc': 'Übersicht aller KI-Agenten',
    'agents.specializedAgentsDesc': 'Medizin- & Automobil-Experten',
    'agents.syncInventory': 'Inventar-Synchronisation',
    'agents.syncInventoryDesc': 'Marktplatz-Inventar-Synchronisation',
    'agents.globalConfig': 'Globale Konfiguration',
    'agents.globalConfigDesc': 'Globale Agent-Einstellungen',
    
    'Specialized AI Agents': 'Spezialisierte KI-Agenten',
    'Expert knowledge for medical devices and automotive components': 'Expertenwissen für Medizinprodukte und Automotive-Komponenten',
    'Configure': 'Konfigurieren',
    'Performance': 'Leistung',
    'Tasks': 'Aufgaben',
    'Active': 'Aktiv',
    'Inactive': 'Inaktiv',
    'Training': 'Training',
    'Error': 'Fehler',
    'Unknown': 'Unbekannt',
    'Agent status updated': 'Agent-Status aktualisiert',
    'Agent training started': 'Agent-Training gestartet',
    'Agent training completed': 'Agent-Training abgeschlossen',
    'Configuration updated': 'Konfiguration aktualisiert',
    'Pause': 'Pausieren',
    'Activate': 'Aktivieren',
    'Retrain': 'Neu trainieren',
    'Overview': 'Übersicht',
    'Expertise': 'Expertise',
    'Configuration': 'Konfiguration',
    'Status & Metrics': 'Status & Metriken',
    'Tasks Completed': 'Erledigte Aufgaben',
    'Category': 'Kategorie',
    'Compliance Standards': 'Compliance-Standards',
    'Supported Languages': 'Unterstützte Sprachen',
    'Core Expertise Areas': 'Kernkompetenzbereiche',
    'Knowledge Base': 'Wissensbasis',
    'Standards Documents': 'Normdokumente',
    'Product Specifications': 'Produktspezifikationen',
    'Compliance Guides': 'Compliance-Leitfäden',
    'Last Knowledge Update': 'Letztes Wissens-Update',
    'Response Quality': 'Antwortqualität',
    'Accuracy': 'Genauigkeit',
    'Compliance Check': 'Compliance-Prüfung',
    'User Satisfaction': 'Benutzerzufriedenheit',
    'Task Statistics': 'Aufgabenstatistiken',
    'Tasks Today': 'Aufgaben heute',
    'Average Response Time': 'Durchschnittliche Antwortzeit',
    'Success Rate': 'Erfolgsrate',
    'Error Rate': 'Fehlerrate',
    'Model Configuration': 'Modellkonfiguration',
    'AI Model': 'KI-Modell',
    'Temperature': 'Temperatur',
    'Max Tokens': 'Max. Tokens',
    'Specialization Settings': 'Spezialisierungseinstellungen',
    'Focus Area': 'Schwerpunktbereich',
    'Medical Devices': 'Medizinprodukte',
    'Automotive Components': 'Automotive-Komponenten',
    'Connectors & Cables': 'Steckverbinder & Kabel',
    'Motors & Sensors': 'Motoren & Sensoren',
    'Active Compliance Standards': 'Aktive Compliance-Standards',
    'Custom Instructions': 'Benutzerdefinierte Anweisungen',
    'Enter specific instructions for this agent...': 'Spezifische Anweisungen für diesen Agenten eingeben...',
    'Cancel': 'Abbrechen',
    'Save Configuration': 'Konfiguration speichern',
    'Configuration saved': 'Konfiguration gespeichert',
    'Management': 'Verwaltung',
    'Live Demo': 'Live-Demo',
    'Basic Demo': 'Basis-Demo',
    'Advanced Demo': 'Erweiterte Demo',
    'Advanced Specialized Agents Demo': 'Erweiterte spezialisierte Agenten Demo',
    'Test specialized AI agents with real Spark LLM integration': 'Testen Sie spezialisierte KI-Agenten mit echter Spark LLM-Integration',
    'Specialized Agents Demo': 'Spezialisierte Agenten Demo',
    'Test specialized AI agents with your product data': 'Testen Sie spezialisierte KI-Agenten mit Ihren Produktdaten',
    'Product Information': 'Produktinformationen',
    'Select Specialized Agent': 'Spezialisierten Agenten auswählen',
    'Product Name': 'Produktname',
    'Product Description': 'Produktbeschreibung',
    'Technical Specifications': 'Technische Spezifikationen',
    'Analyze Product': 'Produkt analysieren',
    'Check Compliance': 'Compliance prüfen',
    'Generate Content': 'Inhalt generieren',
    'Multi-Language': 'Mehrsprachig',
    'Agent Tasks & Results': 'Agent-Aufgaben & Ergebnisse',
    'No tasks yet. Run an agent task to see results.': 'Noch keine Aufgaben. Führen Sie eine Agent-Aufgabe aus, um Ergebnisse zu sehen.',
    
    // Dashboard
    'dashboard.revenue': 'Gesamtumsatz',
    'dashboard.orders': 'Aktive Bestellungen',
    'dashboard.buybox': 'Buy Box %',
    'dashboard.automations': 'KI-Automatisierungen',
    'dashboard.performance': 'Leistungstrends',
    'dashboard.marketplaceRevenue': 'Umsatz nach Marktplatz',
    
    // Agent Performance
    'agents.performance.title': 'Agent-Leistungs-Dashboard',
    'agents.performance.subtitle': 'Überwachen und optimieren Sie die KI-Agent-Leistung mit A/B-Tests',
    
    // Chat
    'chat.aiAssistant': 'KI-Assistent',
    'chat.onlineNow': 'Jetzt online',
    'chat.typeMessage': 'Nachricht eingeben...',
    'chat.helpful': 'Hilfreich?',
    'chat.helpfulFeedback': 'Hilfreiches Feedback erhalten',
    'chat.feedbackReceived': 'Feedback erhalten',
    'chat.poweredBy': 'Angetrieben von Goodlink KI • 24/7 verfügbar',
    'chat.showPopularProducts': 'Zeige mir beliebte Produkte',
    'chat.findMedicalDevices': 'Hilf mir Medizinprodukte zu finden',
    'chat.findAutomotiveParts': 'Zeige Automobilkomponenten',
    'chat.complianceCerts': 'Compliance-Zertifikate',
    'chat.volumePricing': 'Mengenrabatt-Optionen',
    'chat.technicalDocs': 'Technische Dokumentation',
    'chat.bestDeals': 'Was sind eure besten Angebote?',
    'chat.customerSupport': 'Ich brauche Kundensupport',
    'chat.shippingInfo': 'Erzähl mir mehr über Versand',
    'chat.productCategories': 'Zeige mir Produktkategorien',
    'chat.returnsInfo': 'Wie funktionieren Rücksendungen?',
    'chat.humanSupport': 'Menschlichen Support kontaktieren',
    'chat.tryAgain': 'Erneut versuchen',
    'chat.errorResponse': 'Entschuldigung, ich habe gerade Probleme beim Antworten. Bitte versuchen Sie es erneut oder kontaktieren Sie unser menschliches Support-Team.',
    'chat.clearChat': 'Gespräch löschen',
    'chat.closeChat': 'Chat schließen',
    'chat.minimize': 'Minimieren',
    'chat.maximize': 'Maximieren',
    'chat.restore': 'Wiederherstellen',
    'chat.escToClose': 'ESC zum Schließen',
    
    // System Status
    'system.online': 'System Online',
    'system.offline': 'System Offline',
    'system.maintenance': 'Wartungsmodus',
    
    // Language names
    'lang.english': 'English',
    'lang.german': 'Deutsch',
    'lang.chinese': '中文',
    'lang.french': 'Français',
    
    // Login & Auth
    'auth.login': 'Anmelden',
    'auth.register': 'Registrieren',
    'auth.email': 'E-Mail-Adresse',
    'auth.password': 'Passwort',
    'auth.confirmPassword': 'Passwort bestätigen',
    'auth.firstName': 'Vorname',
    'auth.lastName': 'Nachname',
    'auth.company': 'Unternehmen',
    'auth.phone': 'Telefonnummer',
    'auth.rememberMe': 'Angemeldet bleiben',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.noAccount': 'Noch kein Konto?',
    'auth.hasAccount': 'Bereits ein Konto?',
    'auth.signUp': 'Registrieren',
    'auth.signIn': 'Anmelden',
    'auth.signOut': 'Abmelden',
    'auth.createAccount': 'Konto erstellen',
    'auth.welcome': 'Willkommen bei Goodlink Germany',
    'auth.welcomeBack': 'Willkommen zurück',
    'auth.loginDesc': 'Melden Sie sich an, um auf hochwertige Medizinprodukte und Automobilkomponenten zuzugreifen',
    'auth.registerDesc': 'Werden Sie Teil tausender zufriedener B2B-Partner',
    'auth.terms': 'Ich stimme den Nutzungsbedingungen und der Datenschutzerklärung zu',
    'auth.accountType': 'Kontotyp',
    'auth.individual': 'Privatkunde',
    'auth.business': 'Geschäftskonto',
    'auth.customerType': 'Kundentyp',
    'auth.newCustomer': 'Neukunde',
    'auth.returningCustomer': 'Bestandskunde',
    'auth.loggedOut': 'Erfolgreich abgemeldet',
    
    // Account Management
    'account.profile': 'Profil',
    'account.orders': 'Meine Bestellungen',
    'account.settings': 'Einstellungen',
    
    // Client Website
    'client.aboutTitle': 'Über Goodlink Germany',
    'client.aboutDesc': 'Die Good-Link Germany GmbH befindet sich im Herzen Europas in Köln, Deutschland. Wir sind die erste Good-Link-Niederlassung außerhalb Chinas, gegründet 2020 in Zusammenarbeit mit deutschen Aktionären und Management.',
    'client.ourMission': 'Unsere Mission',
    'client.missionDesc': 'Good-Link Germany wird der beste Kanal für europäische Unternehmen, die mit Partnern in China zusammenarbeiten möchten.',
    'client.ourValues': 'Unsere Werte',
    'client.heroTitle': 'Medizin- und Automotive-Exzellenz',
    'client.heroSubtitle': 'Premium Medizinprodukte und Automobilkomponenten. Ihre vertrauensvolle Brücke zwischen Europa und China seit 2020.',
    'client.browseCatalog': 'Katalog durchsuchen',
    'client.learnMore': 'Mehr erfahren',
    'client.whyChoose': 'Warum Goodlink Germany wählen?',
    'client.whyChooseDesc': 'Erleben Sie die Zukunft der B2B-Beschaffung mit unseren innovativen Funktionen und unserem Engagement für Exzellenz.',
    'client.medicalGrade': 'Medizinische Qualität',
    'client.medicalGradeDesc': 'Zertifizierte Medizinprodukte und Automobilkomponenten nach EU/CE-Standards',
    'client.chinaBridge': 'China-EU-Brücke',
    'client.chinaBridgeDesc': 'Direkte Beschaffung von vertrauenswürdigen Herstellern in Shenzhen, Shanghai und Hongkong',
    'client.compliance': 'Compliance gesichert',
    'client.complianceDesc': 'Vollständige regulatorische Compliance für Medizinprodukte (MDR/CE) und Automotive (EMC/ROHS)',
    'client.expertSupport': 'Expertenunterstützung',
    'client.expertSupportDesc': 'Technischer Support von Spezialisten in Deutsch, Englisch und Chinesisch',
    'client.shopByCategory': 'Nach Kategorie einkaufen',
    'client.shopByCategoryDesc': 'Entdecken Sie unser vielfältiges Produktsortiment in verschiedenen Kategorien.',
    'client.medicalDevices': 'Medizinprodukte',
    'client.automotiveParts': 'Automobilteile',
    'client.connectorsCables': 'Steckverbinder & Kabel',
    'client.motorsSensors': 'Motoren & Sensoren',
    'client.mechanicalComponents': 'Mechanische Komponenten',
    'client.readyToStart': 'Bereit zum Einkaufen?',
    'client.readyToStartDesc': 'Werden Sie Teil tausender zufriedener Kunden und entdecken Sie erstaunliche Produkte mit unserer KI-gestützten Beschaffungserfahrung.',
    'client.browseProducts': 'Produkte durchsuchen',
    'client.readBlog': 'Unseren Blog lesen',
    'client.businessCulture': 'Unsere Unternehmenskultur',
    'client.personalRelationships': 'Gute persönliche Beziehungen und eine zuverlässige Arbeitsweise kennzeichnen unseren Ansatz zu unseren Partnern',
    'client.honestCommunication': 'Realistische und ehrliche Kommunikation sorgen für eine effektive und vertrauensvolle Zusammenarbeit',
    'client.culturalBridges': 'Wir sind uns kultureller Unterschiede bewusst und bauen gerne Brücken, um sie zu überbrücken',
    'client.ourTeam': 'Unser Team',
    'client.officesChina': 'Büros in China',
    'client.officesGermany': 'Büros in Deutschland',
    'client.focusMedical': 'Fokus auf Medizin',
    'client.warehouses': 'Warenlager',
    'client.goodlinkChina': 'Good-Link China',
    'client.goodlinkChinaDesc': 'Gegründet 2004, operiert Good-Link China in vier Städten Chinas mit einem Team von 78 Mitarbeitern. Spezialisiert auf die Automobil- und Medizinbranche, sind wir stolz auf unser etabliertes und umfangreiches Netzwerk von Lieferanten und Kunden.',
    'client.components': 'Komponenten',
    'client.partners': 'B2B-Partner',
    'client.experience': 'Jahre Erfahrung',
    'client.revenue': 'Umsatz 2023',
    
    // Cart & Shopping
    'cart.title': 'Warenkorb',
    'cart.empty': 'Ihr Warenkorb ist leer',
    'cart.emptyDesc': 'Fügen Sie einige Produkte hinzu, um zu beginnen',
    'cart.item': 'Artikel',
    'cart.items': 'Artikel',
    'cart.subtotal': 'Zwischensumme',
    'cart.shipping': 'Versand',
    'cart.tax': 'Steuer',
    'cart.total': 'Gesamt',
    'cart.remove': 'Entfernen',
    'cart.update': 'Aktualisieren',
    'cart.checkout': 'Zur Kasse gehen',
    'cart.continueShopping': 'Weiter einkaufen',
    'cart.addedToCart': 'Zum Warenkorb hinzugefügt',
    'cart.removedFromCart': 'Aus Warenkorb entfernt',
    'cart.quantityUpdated': 'Menge aktualisiert',
    
    // Agent Status
    'agents.statusUpdated': 'Agent-Status aktualisiert',
    'agents.configSaved': 'Konfiguration gespeichert',
    'agents.successRate': 'Erfolgsrate',
    'agents.tasks': 'Aufgaben',
    'agents.pause': 'Pausieren',
    'agents.activate': 'Aktivieren',
  },
  
  zh: {
    // Navigation
    'nav.dashboard': '仪表板',
    'nav.marketplaces': '市场平台',
    'nav.products': '产品',
    'nav.inventory': '库存同步',
    'nav.shop': '商店',
    'nav.blog': '博客',
    'nav.whatsapp': 'WhatsApp',
    'nav.agents': 'AI代理',
    'nav.admin': '管理面板',
    'nav.account': '我的账户',
    'nav.cart': '购物车',
    'nav.orders': '我的订单',
    'nav.logout': '退出登录',
    'nav.login': '登录',
    'nav.home': '首页',
    'nav.about': '关于我们',
    'nav.contact': '联系我们',
    'nav.client': '网站',
    
    // Common
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.add': '添加',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.export': '导出',
    'common.import': '导入',
    'common.configure': '配置',
    'common.active': '活跃',
    'common.inactive': '非活跃',
    'common.status': '状态',
    'common.price': '价格',
    'common.quantity': '数量',
    'common.total': '总计',
    'common.view': '查看',
    'common.back': '返回',
    
    // Admin Panel
    'admin.title': '管理控制中心',
    'admin.overview': '系统概览',
    'admin.users': '用户管理',
    'admin.settings': '全局设置',
    'admin.analytics': '高级分析',
    'admin.logs': '系统日志',
    'admin.coreManagement': '核心管理',
    'admin.configuration': '配置',
    'admin.aiAutomation': 'AI与自动化',
    'admin.systemMonitoring': '系统与监控',
    'admin.shopConfig': '商店配置',
    'admin.blogConfig': '博客配置',
    'admin.sync': '同步',
    'admin.monitoring': '监控',
    'admin.userManagement': '用户管理系统',
    'admin.userManagementDesc': '管理用户账户、权限和访问控制',
    
    // Shop
    'shop.title': 'Goodlink 商店',
    'shop.categories': '分类',
    'shop.featured': '精选产品',
    'shop.bestsellers': '畅销产品',
    'shop.new': '新品上市',
    'shop.addToCart': '添加到购物车',
    'shop.buyNow': '立即购买',
    'shop.outOfStock': '缺货',
    'shop.inStock': '现货',
    'shop.productDetails': '产品详情',
    'shop.reviews': '客户评价',
    'shop.relatedProducts': '相关产品',
    'shop.checkout': '结账',
    'shop.cart': '购物车',
    'shop.cartEmpty': '您的购物车是空的',
    'shop.continueShopping': '继续购物',
    'shop.proceedToCheckout': '去结账',
    
    // User Account
    'user.profile': '个人资料',
    'user.orders': '订单历史',
    'user.addresses': '地址',
    'user.payment': '支付方式',
    'user.preferences': '偏好设置',
    'user.notifications': '通知',
    'user.security': '安全',
    'user.welcome': '欢迎回来',
    
    // AI Agents
    'agents.title': 'AI代理控制中心',
    'agents.active': '活跃代理',
    'agents.training': '训练中',
    'agents.success': '平均成功率',
    'agents.processed': '总处理量',
    'agents.social': '社交媒体',
    'agents.messaging': '消息传递',
    'agents.content': '内容',
    'agents.pricing': '定价',
    'agents.analytics': '分析',
    'agents.forecasting': '预测',
    'agents.support': '支持',
    
    // Specialized Agents
    'agents.allAgents': '所有代理',
    'agents.specializedAgents': '专业代理',
    'agents.categoryExperts': '产品类别专家',
    'agents.allAgentsDesc': '所有AI代理概览',
    'agents.specializedAgentsDesc': '医疗和汽车专家',
    'agents.syncInventory': '库存同步',
    'agents.syncInventoryDesc': '市场平台库存同步',
    'agents.globalConfig': '全局配置',
    'agents.globalConfigDesc': '全局代理设置',
    
    'Specialized AI Agents': '专业AI代理',
    'Expert knowledge for medical devices and automotive components': '医疗设备和汽车零部件的专业知识',
    'Configure': '配置',
    'Performance': '性能',
    'Tasks': '任务',
    'Active': '活跃',
    'Inactive': '非活跃',
    'Training': '训练中',
    'Error': '错误',
    'Unknown': '未知',
    'Agent status updated': '代理状态已更新',
    'Agent training started': '代理训练已开始',
    'Agent training completed': '代理训练已完成',
    'Configuration updated': '配置已更新',
    'Pause': '暂停',
    'Activate': '激活',
    'Retrain': '重新训练',
    'Overview': '概览',
    'Expertise': '专业技能',
    'Configuration': '配置',
    'Status & Metrics': '状态和指标',
    'Tasks Completed': '已完成任务',
    'Category': '类别',
    'Compliance Standards': '合规标准',
    'Supported Languages': '支持的语言',
    'Core Expertise Areas': '核心专业领域',
    'Knowledge Base': '知识库',
    'Standards Documents': '标准文档',
    'Product Specifications': '产品规格',
    'Compliance Guides': '合规指南',
    'Last Knowledge Update': '最后知识更新',
    'Response Quality': '响应质量',
    'Accuracy': '准确性',
    'Compliance Check': '合规检查',
    'User Satisfaction': '用户满意度',
    'Task Statistics': '任务统计',
    'Tasks Today': '今日任务',
    'Average Response Time': '平均响应时间',
    'Success Rate': '成功率',
    'Error Rate': '错误率',
    'Model Configuration': '模型配置',
    'AI Model': 'AI模型',
    'Temperature': '温度',
    'Max Tokens': '最大令牌',
    'Specialization Settings': '专业化设置',
    'Focus Area': '重点领域',
    'Medical Devices': '医疗设备',
    'Automotive Components': '汽车零部件',
    'Connectors & Cables': '连接器和电缆',
    'Motors & Sensors': '电机和传感器',
    'Active Compliance Standards': '活跃合规标准',
    'Custom Instructions': '自定义指令',
    'Enter specific instructions for this agent...': '为此代理输入特定指令...',
    'Cancel': '取消',
    'Save Configuration': '保存配置',
    'Configuration saved': '配置已保存',
    'Management': '管理',
    'Live Demo': '实时演示',
    'Basic Demo': '基础演示',
    'Advanced Demo': '高级演示',
    'Advanced Specialized Agents Demo': '高级专业代理演示',
    'Test specialized AI agents with real Spark LLM integration': '使用真实的Spark LLM集成测试专业AI代理',
    'Specialized Agents Demo': '专业代理演示',
    'Test specialized AI agents with your product data': '使用您的产品数据测试专业AI代理',
    'Product Information': '产品信息',
    'Select Specialized Agent': '选择专业代理',
    'Product Name': '产品名称',
    'Product Description': '产品描述',
    'Technical Specifications': '技术规格',
    'Analyze Product': '分析产品',
    'Check Compliance': '检查合规性',
    'Generate Content': '生成内容',
    'Multi-Language': '多语言',
    'Agent Tasks & Results': '代理任务和结果',
    'No tasks yet. Run an agent task to see results.': '还没有任务。运行代理任务以查看结果。',
    
    // Dashboard
    'dashboard.revenue': '总收入',
    'dashboard.orders': '活跃订单',
    'dashboard.buybox': 'Buy Box %',
    'dashboard.automations': 'AI自动化',
    'dashboard.performance': '性能趋势',
    'dashboard.marketplaceRevenue': '按市场平台的收入',
    
    // Agent Performance
    'agents.performance.title': '代理性能仪表板',
    'agents.performance.subtitle': '通过A/B测试监控和优化AI代理性能',
    
    // Chat
    'chat.aiAssistant': 'AI助手',
    'chat.onlineNow': '现在在线',
    'chat.typeMessage': '输入您的消息...',
    'chat.helpful': '有帮助吗？',
    'chat.helpfulFeedback': '收到有用反馈',
    'chat.feedbackReceived': '已收到反馈',
    'chat.poweredBy': 'Goodlink AI 驱动 • 24/7 可用',
    'chat.showPopularProducts': '给我看热门产品',
    'chat.findMedicalDevices': '帮我找医疗设备',
    'chat.findAutomotiveParts': '显示汽车零部件',
    'chat.complianceCerts': '合规证书',
    'chat.volumePricing': '批量定价选项',
    'chat.technicalDocs': '技术文档',
    'chat.bestDeals': '你们最好的优惠是什么？',
    'chat.customerSupport': '我需要客户支持',
    'chat.shippingInfo': '告诉我更多关于运输的信息',
    'chat.productCategories': '给我看产品类别',
    'chat.returnsInfo': '退货如何工作？',
    'chat.humanSupport': '联系人工支持',
    'chat.tryAgain': '再试一次',
    'chat.errorResponse': '抱歉，我现在回复有困难。请重试或联系我们的人工支持团队。',
    'chat.clearChat': '清除对话',
    'chat.closeChat': '关闭聊天',
    'chat.minimize': '最小化',
    'chat.maximize': '最大化',
    'chat.restore': '恢复',
    'chat.escToClose': 'ESC键关闭',
    
    // System Status
    'system.online': '系统在线',
    'system.offline': '系统离线',
    'system.maintenance': '维护模式',
    
    // Language names
    'lang.english': 'English',
    'lang.german': 'Deutsch',
    'lang.chinese': '中文',
    'lang.french': 'Français',
    
    // Login & Auth
    'auth.login': '登录',
    'auth.register': '注册',
    'auth.email': '电子邮箱',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.firstName': '名',
    'auth.lastName': '姓',
    'auth.company': '公司',
    'auth.phone': '电话号码',
    'auth.rememberMe': '记住我',
    'auth.forgotPassword': '忘记密码？',
    'auth.noAccount': '还没有账户？',
    'auth.hasAccount': '已有账户？',
    'auth.signUp': '注册',
    'auth.signIn': '登录',
    'auth.signOut': '退出登录',
    'auth.createAccount': '创建账户',
    'auth.welcome': '欢迎来到Goodlink Germany',
    'auth.welcomeBack': '欢迎回来',
    'auth.loginDesc': '登录以访问优质医疗设备和汽车零部件',
    'auth.registerDesc': '加入数千满意的B2B合作伙伴',
    'auth.terms': '我同意服务条款和隐私政策',
    'auth.accountType': '账户类型',
    'auth.individual': '个人客户',
    'auth.business': '企业账户',
    'auth.customerType': '客户类型',
    'auth.newCustomer': '新客户',
    'auth.returningCustomer': '老客户',
    'auth.loggedOut': '成功退出登录',
    
    // Account Management
    'account.profile': '个人资料',
    'account.orders': '我的订单',
    'account.settings': '设置',
    
    // Client Website
    'client.aboutTitle': '关于Goodlink Germany',
    'client.aboutDesc': 'Good-Link Germany GmbH位于欧洲中心德国科隆。我们是Good-Link在中国以外的第一个分支机构，成立于2020年，与德国股东和管理层合作。',
    'client.ourMission': '我们的使命',
    'client.missionDesc': 'Good-Link Germany将成为希望与中国合作伙伴合作的欧洲公司的最佳渠道。',
    'client.ourValues': '我们的价值观',
    'client.heroTitle': '医疗与汽车卓越',
    'client.heroSubtitle': '优质医疗设备和汽车零部件。自2020年以来，您在欧洲和中国之间值得信赖的桥梁。',
    'client.browseCatalog': '浏览目录',
    'client.learnMore': '了解更多',
    'client.whyChoose': '为什么选择Goodlink Germany？',
    'client.whyChooseDesc': '通过我们的创新功能和对卓越的承诺，体验B2B采购的未来。',
    'client.medicalGrade': '医疗级质量',
    'client.medicalGradeDesc': '符合EU/CE标准的认证医疗设备和汽车零部件',
    'client.chinaBridge': '中欧桥梁',
    'client.chinaBridgeDesc': '直接从深圳、上海和香港的可信制造商采购',
    'client.compliance': '合规保证',
    'client.complianceDesc': '医疗设备(MDR/CE)和汽车(EMC/ROHS)的完全法规合规',
    'client.expertSupport': '专家支持',
    'client.expertSupportDesc': '德语、英语和中文专家技术支持',
    'client.shopByCategory': '按类别购物',
    'client.shopByCategoryDesc': '探索我们跨多个类别的多样化产品范围。',
    'client.medicalDevices': '医疗设备',
    'client.automotiveParts': '汽车零部件',
    'client.connectorsCables': '连接器和电缆',
    'client.motorsSensors': '电机和传感器',
    'client.mechanicalComponents': '机械零部件',
    'client.readyToStart': '准备开始购物？',
    'client.readyToStartDesc': '加入数千满意的客户，通过我们的AI驱动采购体验发现优质产品。',
    'client.browseProducts': '浏览产品',
    'client.readBlog': '阅读我们的博客',
    'client.businessCulture': '我们的企业文化',
    'client.personalRelationships': '良好的个人关系和可靠的工作方式是我们对合作伙伴的特点',
    'client.honestCommunication': '现实和诚实的沟通确保有效和可信的合作',
    'client.culturalBridges': '我们意识到文化差异，喜欢搭建桥梁来跨越它们',
    'client.ourTeam': '我们的团队',
    'client.officesChina': '中国办事处',
    'client.officesGermany': '德国办事处',
    'client.focusMedical': '专注医疗',
    'client.warehouses': '仓库',
    'client.goodlinkChina': 'Good-Link China',
    'client.goodlinkChinaDesc': '成立于2004年，Good-Link China在中国四个城市运营，拥有78名员工团队。专门从事汽车和医疗行业，我们为我们建立的广泛供应商和客户网络感到自豪。',
    'client.components': '组件',
    'client.partners': 'B2B合作伙伴',
    'client.experience': '年经验',
    'client.revenue': '2023年收入',
    
    // Cart & Shopping
    'cart.title': '购物车',
    'cart.empty': '您的购物车是空的',
    'cart.emptyDesc': '添加一些产品开始购物',
    'cart.item': '项',
    'cart.items': '项',
    'cart.subtotal': '小计',
    'cart.shipping': '运费',
    'cart.tax': '税费',
    'cart.total': '总计',
    'cart.remove': '移除',
    'cart.update': '更新',
    'cart.checkout': '去结账',
    'cart.continueShopping': '继续购物',
    'cart.addedToCart': '已添加到购物车',
    'cart.removedFromCart': '已从购物车移除',
    'cart.quantityUpdated': '数量已更新',
    
    // Agent Status
    'agents.statusUpdated': '代理状态已更新',
    'agents.configSaved': '配置已保存',
    'agents.successRate': '成功率',
    'agents.tasks': '任务',
    'agents.pause': '暂停',
    'agents.activate': '激活',
  },
  
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.marketplaces': 'Places de marché',
    'nav.products': 'Produits',
    'nav.inventory': 'Sync inventaire',
    'nav.shop': 'Boutique',
    'nav.blog': 'Blog',
    'nav.whatsapp': 'WhatsApp',
    'nav.agents': 'Agents IA',
    'nav.admin': 'Panneau Admin',
    'nav.account': 'Mon compte',
    'nav.cart': 'Panier',
    'nav.orders': 'Mes commandes',
    'nav.logout': 'Déconnexion',
    'nav.login': 'Connexion',
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'nav.client': 'Site web',
    
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.add': 'Ajouter',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.export': 'Exporter',
    'common.import': 'Importer',
    'common.configure': 'Configurer',
    'common.active': 'Actif',
    'common.inactive': 'Inactif',
    'common.status': 'Statut',
    'common.price': 'Prix',
    'common.quantity': 'Quantité',
    'common.total': 'Total',
    'common.view': 'Voir',
    'common.back': 'Retour',
    
    // Admin Panel
    'admin.title': 'Centre de contrôle Admin',
    'admin.overview': 'Vue d\'ensemble du système',
    'admin.users': 'Gestion des utilisateurs',
    'admin.settings': 'Paramètres globaux',
    'admin.analytics': 'Analyses avancées',
    'admin.logs': 'Journaux système',
    'admin.coreManagement': 'Gestion principale',
    'admin.configuration': 'Configuration',
    'admin.aiAutomation': 'IA et automatisation',
    'admin.systemMonitoring': 'Système et surveillance',
    'admin.shopConfig': 'Configuration boutique',
    'admin.blogConfig': 'Configuration blog',
    'admin.sync': 'Synchronisation',
    'admin.monitoring': 'Surveillance',
    'admin.userManagement': 'Système de gestion des utilisateurs',
    'admin.userManagementDesc': 'Gérer les comptes utilisateurs, les permissions et le contrôle d\'accès',
    
    // Shop
    'shop.title': 'Boutique Goodlink',
    'shop.categories': 'Catégories',
    'shop.featured': 'Produits vedettes',
    'shop.bestsellers': 'Meilleures ventes',
    'shop.new': 'Nouveautés',
    'shop.addToCart': 'Ajouter au panier',
    'shop.buyNow': 'Acheter maintenant',
    'shop.outOfStock': 'Rupture de stock',
    'shop.inStock': 'En stock',
    'shop.productDetails': 'Détails du produit',
    'shop.reviews': 'Avis clients',
    'shop.relatedProducts': 'Produits similaires',
    'shop.checkout': 'Commander',
    'shop.cart': 'Panier',
    'shop.cartEmpty': 'Votre panier est vide',
    'shop.continueShopping': 'Continuer les achats',
    'shop.proceedToCheckout': 'Passer la commande',
    
    // User Account
    'user.profile': 'Profil',
    'user.orders': 'Historique des commandes',
    'user.addresses': 'Adresses',
    'user.payment': 'Moyens de paiement',
    'user.preferences': 'Préférences',
    'user.notifications': 'Notifications',
    'user.security': 'Sécurité',
    'user.welcome': 'Bon retour',
    
    // AI Agents
    'agents.title': 'Centre de contrôle des agents IA',
    'agents.active': 'Agents actifs',
    'agents.training': 'Formation',
    'agents.success': 'Taux de réussite moyen',
    'agents.processed': 'Total traité',
    'agents.social': 'Médias sociaux',
    'agents.messaging': 'Messagerie',
    'agents.content': 'Contenu',
    'agents.pricing': 'Tarification',
    'agents.analytics': 'Analytique',
    'agents.forecasting': 'Prévision',
    'agents.support': 'Support',
    
    // Specialized Agents
    'agents.allAgents': 'Tous les agents',
    'agents.specializedAgents': 'Agents spécialisés',
    'agents.categoryExperts': 'Experts par catégorie de produits',
    'agents.allAgentsDesc': 'Vue d\'ensemble de tous les agents IA',
    'agents.specializedAgentsDesc': 'Experts médicaux et automobiles',
    'agents.syncInventory': 'Synchronisation inventaire',
    'agents.syncInventoryDesc': 'Synchronisation inventaire des marchés',
    'agents.globalConfig': 'Configuration globale',
    'agents.globalConfigDesc': 'Paramètres globaux des agents',
    
    // Dashboard
    'dashboard.revenue': 'Chiffre d\'affaires total',
    'dashboard.orders': 'Commandes actives',
    'dashboard.buybox': 'Buy Box %',
    'dashboard.automations': 'Automatisations IA',
    'dashboard.performance': 'Tendances de performance',
    'dashboard.marketplaceRevenue': 'Revenus par place de marché',
    
    // Agent Performance
    'agents.performance.title': 'Tableau de bord de performance des agents',
    'agents.performance.subtitle': 'Surveillez et optimisez les performances des agents IA avec des tests A/B',
    
    // Chat
    'chat.aiAssistant': 'Assistant IA',
    'chat.onlineNow': 'En ligne maintenant',
    'chat.typeMessage': 'Tapez votre message...',
    'chat.helpful': 'Utile?',
    'chat.helpfulFeedback': 'Retour utile reçu',
    'chat.feedbackReceived': 'Retour reçu',
    'chat.poweredBy': 'Alimenté par Goodlink IA • Disponible 24/7',
    'chat.showPopularProducts': 'Montrez-moi les produits populaires',
    'chat.findMedicalDevices': 'Aidez-moi à trouver des dispositifs médicaux',
    'chat.findAutomotiveParts': 'Montrez les composants automobiles',
    'chat.complianceCerts': 'Certificats de conformité',
    'chat.volumePricing': 'Options de tarification en volume',
    'chat.technicalDocs': 'Documentation technique',
    'chat.bestDeals': 'Quelles sont vos meilleures offres?',
    'chat.customerSupport': 'J\'ai besoin du support client',
    'chat.shippingInfo': 'Parlez-moi plus de la livraison',
    'chat.productCategories': 'Montrez-moi les catégories de produits',
    'chat.returnsInfo': 'Comment fonctionnent les retours?',
    'chat.humanSupport': 'Contacter le support humain',
    'chat.tryAgain': 'Réessayer',
    'chat.errorResponse': 'Je m\'excuse, j\'ai des difficultés à répondre maintenant. Veuillez réessayer ou contacter notre équipe de support humain.',
    'chat.clearChat': 'Effacer la conversation',
    'chat.closeChat': 'Fermer le chat',
    'chat.minimize': 'Réduire',
    'chat.maximize': 'Agrandir',
    'chat.restore': 'Restaurer',
    'chat.escToClose': 'ESC pour fermer',
    
    // System Status
    'system.online': 'Système en ligne',
    'system.offline': 'Système hors ligne',
    'system.maintenance': 'Mode maintenance',
    
    // Language names
    'lang.english': 'English',
    'lang.german': 'Deutsch',
    'lang.chinese': '中文',
    'lang.french': 'Français',
    
    // Login & Auth
    'auth.login': 'Connexion',
    'auth.register': 'S\'inscrire',
    'auth.email': 'Adresse e-mail',
    'auth.password': 'Mot de passe',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.firstName': 'Prénom',
    'auth.lastName': 'Nom de famille',
    'auth.company': 'Entreprise',
    'auth.phone': 'Numéro de téléphone',
    'auth.rememberMe': 'Se souvenir de moi',
    'auth.forgotPassword': 'Mot de passe oublié?',
    'auth.noAccount': 'Pas encore de compte?',
    'auth.hasAccount': 'Déjà un compte?',
    'auth.signUp': 'S\'inscrire',
    'auth.signIn': 'Se connecter',
    'auth.signOut': 'Se déconnecter',
    'auth.createAccount': 'Créer un compte',
    'auth.welcome': 'Bienvenue chez Goodlink Germany',
    'auth.welcomeBack': 'Bon retour',
    'auth.loginDesc': 'Connectez-vous pour accéder aux dispositifs médicaux premium et composants automobiles',
    'auth.registerDesc': 'Rejoignez des milliers de partenaires B2B satisfaits',
    'auth.terms': 'J\'accepte les Conditions de Service et la Politique de Confidentialité',
    'auth.accountType': 'Type de compte',
    'auth.individual': 'Client individuel',
    'auth.business': 'Compte professionnel',
    'auth.customerType': 'Type de client',
    'auth.newCustomer': 'Nouveau client',
    'auth.returningCustomer': 'Client existant',
    'auth.loggedOut': 'Déconnecté avec succès',
    
    // Account Management
    'account.profile': 'Profil',
    'account.orders': 'Mes commandes',
    'account.settings': 'Paramètres',
    
    // Client Website
    'client.aboutTitle': 'À propos de Goodlink Germany',
    'client.aboutDesc': 'Good-Link Germany GmbH est situé au cœur de l\'Europe à Cologne, Allemagne. Nous sommes la première filiale Good-Link hors de Chine, fondée en 2020 en coopération avec des actionnaires et une direction allemands.',
    'client.ourMission': 'Notre Mission',
    'client.missionDesc': 'Good-Link Germany deviendra le meilleur canal pour les entreprises européennes qui souhaitent coopérer avec des partenaires en Chine.',
    'client.ourValues': 'Nos Valeurs',
    'client.heroTitle': 'Excellence Médicale et Automobile',
    'client.heroSubtitle': 'Dispositifs médicaux premium et composants automobiles. Votre pont de confiance entre l\'Europe et la Chine depuis 2020.',
    'client.browseCatalog': 'Parcourir le catalogue',
    'client.learnMore': 'En savoir plus',
    'client.whyChoose': 'Pourquoi choisir Goodlink Germany?',
    'client.whyChooseDesc': 'Découvrez l\'avenir de l\'approvisionnement B2B avec nos fonctionnalités innovantes et notre engagement envers l\'excellence.',
    'client.medicalGrade': 'Qualité médicale',
    'client.medicalGradeDesc': 'Dispositifs médicaux certifiés et composants automobiles conformes aux normes EU/CE',
    'client.chinaBridge': 'Pont Chine-UE',
    'client.chinaBridgeDesc': 'Approvisionnement direct auprès de fabricants de confiance à Shenzhen, Shanghai et Hong Kong',
    'client.compliance': 'Conformité assurée',
    'client.complianceDesc': 'Conformité réglementaire complète pour dispositifs médicaux (MDR/CE) et automobile (EMC/ROHS)',
    'client.expertSupport': 'Support expert',
    'client.expertSupportDesc': 'Support technique par des spécialistes en allemand, anglais et chinois',
    'client.shopByCategory': 'Acheter par catégorie',
    'client.shopByCategoryDesc': 'Explorez notre gamme diversifiée de produits dans plusieurs catégories.',
    'client.medicalDevices': 'Dispositifs médicaux',
    'client.automotiveParts': 'Pièces automobiles',
    'client.connectorsCables': 'Connecteurs et câbles',
    'client.motorsSensors': 'Moteurs et capteurs',
    'client.mechanicalComponents': 'Composants mécaniques',
    'client.readyToStart': 'Prêt à commencer vos achats?',
    'client.readyToStartDesc': 'Rejoignez des milliers de clients satisfaits et découvrez des produits extraordinaires avec notre expérience d\'approvisionnement alimentée par l\'IA.',
    'client.browseProducts': 'Parcourir les produits',
    'client.readBlog': 'Lire notre blog',
    'client.businessCulture': 'Notre culture d\'entreprise',
    'client.personalRelationships': 'De bonnes relations personnelles et une façon de travailler fiable caractérisent notre approche avec nos partenaires',
    'client.honestCommunication': 'Une communication réaliste et honnête assure une coopération efficace et de confiance',
    'client.culturalBridges': 'Nous sommes conscients des différences culturelles et aimons construire des ponts pour les franchir',
    'client.ourTeam': 'Notre équipe',
    'client.officesChina': 'Bureaux en Chine',
    'client.officesGermany': 'Bureaux en Allemagne',
    'client.focusMedical': 'Focus médical',
    'client.warehouses': 'Entrepôts',
    'client.goodlinkChina': 'Good-Link China',
    'client.goodlinkChinaDesc': 'Fondé en 2004, Good-Link China opère dans quatre villes de Chine avec une équipe de 78 employés. Spécialisés dans les secteurs automobile et médical, nous sommes fiers de notre réseau établi et étendu de fournisseurs et clients.',
    'client.components': 'composants',
    'client.partners': 'Partenaires B2B',
    'client.experience': 'Années d\'expérience',
    'client.revenue': 'Chiffre d\'affaires 2023',
    
    // Cart & Shopping
    'cart.title': 'Panier',
    'cart.empty': 'Votre panier est vide',
    'cart.emptyDesc': 'Ajoutez quelques produits pour commencer',
    'cart.item': 'article',
    'cart.items': 'articles',
    'cart.subtotal': 'Sous-total',
    'cart.shipping': 'Livraison',
    'cart.tax': 'Taxe',
    'cart.total': 'Total',
    'cart.remove': 'Supprimer',
    'cart.update': 'Mettre à jour',
    'cart.checkout': 'Passer la commande',
    'cart.continueShopping': 'Continuer les achats',
    'cart.addedToCart': 'Ajouté au panier',
    'cart.removedFromCart': 'Retiré du panier',
    'cart.quantityUpdated': 'Quantité mise à jour',
    
    // Agent Status
    'agents.statusUpdated': 'Statut de l\'agent mis à jour',
    'agents.configSaved': 'Configuration sauvegardée',
    'agents.successRate': 'Taux de succès',
    'agents.tasks': 'Tâches',
    'agents.pause': 'Pause',
    'agents.activate': 'Activer',
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useKV<Language>('app-language', 'en')

  const t = (key: string): string => {
    try {
      const currentLang = language || 'en'
      // Ensure the language is valid
      const validLang = ['en', 'de', 'zh', 'fr'].includes(currentLang) ? currentLang : 'en'
      return translations[validLang as Language]?.[key] || translations.en[key] || key
    } catch (error) {
      console.warn('Translation error for key:', key, error)
      return key
    }
  }

  const safeSetLanguage = (lang: Language) => {
    try {
      // Validate language before setting
      if (['en', 'de', 'zh', 'fr'].includes(lang)) {
        setLanguage(lang)
      } else {
        console.warn('Invalid language:', lang, 'defaulting to English')
        setLanguage('en')
      }
    } catch (error) {
      console.error('Error setting language:', error)
      setLanguage('en')
    }
  }

  const contextValue = {
    language: language || 'en',
    setLanguage: safeSetLanguage,
    t
  }

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}